name: Valdate CloudFormation Template on PR

on:
  pull_request:
    paths: 
     - 'cloudformation/**'

permissions: 
  pull-requests: write
  contents: read 

jobs:  
  validate-cfn: 
  runs-on: ubuntu 
  steps: 
   - name: actions/checkout@v2

   - name: Configure AWS Credentials 
     uses: aws-actions/configure-aws-credentials@v1
     with: 
       aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID}}
       aws_secret-access-key: ${{ secrets_AWS_SECRET_ACCESS_KEY}}
       region: us-east-1 

       name: Validate CloudFormation Template 
       run: |
         aws cloudformation validate-template --template-body file://cloudformation/template.yaml 

       name: Deploy our Stack 
       run: | 
          stack_name="pr-test-stack-${{github.event.pull_request.number}}"
          aws cloudformation create-stack --stack-name $stack_name --template-body file://cloudformation/template/s3-bucket.yaml --parameters ParameterKey=Environment,ParameterValue=dev 

       name: comment on the PR 
       uses: actions/github-script@v3
       with: 
         github-token : ${{secrets.GITHUB_TOKEN}}
         script: |
           github.rest.issue.createComment{{
           issue_number: context.issue.number,
           owner: context.repo.owner,
           repo: context.repo.repo,
           body: ' Cloudformation test stack deployed. stack name: PR-test-stack-${{github.event.pull_request.number }}'
           }}